image: Visual Studio 2015

version: '0.5.{build}.1'

configuration: Release

assembly_info:
  patch: true
  file: SoftVis.Diagramming\Include\VersionInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: >-
    cd SoftVis.Diagramming
    nuget restore

build:
  project: SoftVis.Diagramming\SoftVis.Diagramming.sln
  verbosity: minimal

test:
  assemblies: '**\*UnitTests.dll'

artifacts:
- path: SoftVis.Diagramming\SoftVis.VisualStudioIntegration\bin\Release\QuickDiagramTool.vsix