image: Visual Studio 2015

version: '0.5.{build}.0'

configuration: Release

assembly_info:
  patch: true
  file: source\include\VersionInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: >-
    cd source

    nuget restore

build:
  project: source\QuickDiagramTool.sln
  verbosity: minimal

test:
  assemblies: '**\*UnitTests.dll'

artifacts:
- path: source\SoftVis.VisualStudioIntegration\bin\Release\QuickDiagramTool.vsix