image: Visual Studio 2015

version: '0.5.{build}.0'

configuration: Release

install:
- ps: (New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/realvizu/softvis/master/tools/build/buildtools.ps1") | Invoke-Expression

assembly_info:
  patch: true
  file: 'source\include\VersionInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- ps: Set-VsixVersion 'source\SoftVis.VisualStudioIntegration\source.extension.vsixmanifest' '{version}'

- cmd: >-
    cd source

    nuget restore

build:
  project: source\QuickDiagramTool.sln
  verbosity: minimal

test:
  assemblies: '**\*UnitTests.dll'

artifacts:
- path: source\SoftVis.VisualStudioIntegration\bin\Release\QuickDiagramTool.vsix